#!/bin/bash
#
LU=/home/wlan/projekty/rpipanel
RPI=/home/pi/py/tk/rpipanel
CMD=rpipanel.py
#
HARDWARE=`uname -m`
#
if [ "$HARDWARE" == "x86_64" ]; then
    cd $LU
else
    cd $RPI
    export DISPLAY=:0
fi
#
#echo `pwd`
python3 $CMD >/dev/null 2>&1
