#!/bin/bash
#
LU=/home/wlan/projekty/rpipanel
RPI=/home/pi/py/tk/rpipanel
#
HARDWARE=`uname -m`
#
if [ "$HARDWARE" == "x86_64" ]; then
    cd $LU
    START=tk01.py
else
    cd $RPI
    START=ap01.py
    export DISPLAY=:0
fi 
#       
#echo `pwd`
python3 $START
